### PR TITLE
Use juggler@3 for running the tests

### PR DESCRIPTION
**Pull request by 0candy**
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1040

### CODE REVIEW

**Comment by 0candy** [comment]
@superkhau / @bajtos PTAL

**Comment by superkhau** [comment]
LGTM

**Comment by superkhau** [comment]
:ship: The downstream is unrelated IMO.

**Comment by bajtos** [comment]
> The downstream is unrelated IMO.

Yes. As I commented elsewhere, dbload-example-app is a fork of a personal project that hasn't been changed in more than a year. I have removed the repository from github.

**Pull request merged**
